<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.9" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Shared\Shared.Api\Shared.Api.csproj" />
      <ProjectReference Include="..\..\Shared\Shared.Domain\Shared.Domain.csproj" />
      <ProjectReference Include="..\BookingService.Application\BookingService.Application.csproj" />
      <ProjectReference Include="..\BookingService.Infrastructure\BookingService.Infrastructure.csproj" />
    </ItemGroup>

</Project>
