<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Options">
        <HintPath>..\..\..\..\.nuget\packages\microsoft.extensions.options\10.0.4\lib\net10.0\Microsoft.Extensions.Options.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared.Domain\Shared.Domain.csproj" />
      <ProjectReference Include="..\UserService.Application\UserService.Application.csproj" />
      <ProjectReference Include="..\UserService.Domain\UserService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    </ItemGroup>

</Project>
